//------------------------------------------------------------------------
// Copyright(c) 2026 Cloves Plugins.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"vintage_hard_distortion_vst3.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Vintage Hard Distortion VST3 (64Bit)"
#else
#define stringFileDescription	"Vintage Hard Distortion VST3"
#endif
#define stringCompanyName		"Cloves Plugins\0"
#define stringLegalCopyright	"Copyright(c) 2026 Cloves Plugins."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
